'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { getSupabase } from '../../lib/supabase'

const fallback = [
  { vacancy_id:'FM-2026-001', organization:'CSIR-CMERI', post:'Technician-I (Group-II) - Foundryman', state:'West Bengal', location:'Durgapur', job_type:'Permanent', status:'Closed', live_status:'Closed', verification_status:'Verified - Official Doc', eligibility:'ITI Foundryman', last_date:'2026-09-13', vacancy_count:null, official_notification_url:'https://www.cmeri.res.in/hi/vacancy', official_apply_url:null, foundryman_eligibility_evidence:'Official CSIR-CMERI vacancy page lists Technician-I recruitment and Foundryman trade eligibility.' },
  { vacancy_id:'FM-2026-002', organization:'DRDO-DRDL', post:'ITI Apprentice - Foundryman', state:'Telangana', location:'DRDL, Hyderabad', job_type:'Apprenticeship', status:'Closed', live_status:'Closed', verification_status:'Verified - Official Doc', eligibility:'ITI Foundryman', last_date:'2026-01-29', vacancy_count:null, official_notification_url:'https://www.drdo.gov.in/drdo/sites/default/files/vacancy/advtDRDL15012026.pdf', official_apply_url:'https://www.apprenticeshipindia.gov.in/', foundryman_eligibility_evidence:'Official DRDL notification explicitly lists Foundryman among ITI apprentice trades.' },
  { vacancy_id:'FM-2026-003', organization:'West Central Railway', post:'Blacksmith (Foundryman) Apprentice', state:'Madhya Pradesh', location:'Jabalpur / Bhopal / Kota', job_type:'Apprenticeship', status:'Closed', live_status:'Closed', verification_status:'Verified - Official Doc', eligibility:'Foundryman / Blacksmith (Foundryman)', last_date:null, vacancy_count:139, official_notification_url:'https://wcr.indianrailways.gov.in/', official_apply_url:null, foundryman_eligibility_evidence:'Official WCR notification explicitly lists Blacksmith (Foundryman).' },
  { vacancy_id:'FM-2026-004', organization:'BHEL Haridwar', post:'Artisan - Foundryman', state:'Uttarakhand', location:'Haridwar', job_type:'Permanent', status:'Closed', live_status:'Closed', verification_status:'Verified - Official Doc', eligibility:'ITI Foundryman', last_date:null, vacancy_count:null, official_notification_url:'https://hwr.bhel.com/recruitment/', official_apply_url:null, foundryman_eligibility_evidence:'BHEL Haridwar recruitment records identify Foundryman trade.' },
  { vacancy_id:'FM-2026-005', organization:'UPSC / DGT', post:'Training Officer - Foundryman/Moulder', state:'All India', location:'DGT / All India service liability', job_type:'Permanent', status:'Closed', live_status:'Closed', verification_status:'Verified - Official Doc', eligibility:'Foundryman / Moulder', last_date:null, vacancy_count:1, official_notification_url:'https://upsc.gov.in/recruitment', official_apply_url:null, foundryman_eligibility_evidence:'UPSC advertisement identifies Training Officer vacancy for Foundryman/Moulder under DGT.' }
]
function daysLeft(date){if(!date)return null;const a=new Date();a.setHours(0,0,0,0);return Math.ceil((new Date(date+'T00:00:00')-a)/86400000)}
export default function Vacancies(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[state,setState]=useState('All'),[type,setType]=useState('All'),[status,setStatus]=useState('Open + Closed'),[verified,setVerified]=useState('All')
 useEffect(()=>{(async()=>{const sb=getSupabase();if(!sb){setRows(fallback);setLoading(false);return}const {data,error}=await sb.from('vacancy_dashboard').select('*').order('last_date',{ascending:true,nullsFirst:false});setRows(error||!data?.length?fallback:data);setLoading(false)})()},[])
 const states=useMemo(()=>['All',...new Set(rows.map(v=>v.state).filter(Boolean))],[rows]); const types=useMemo(()=>['All',...new Set(rows.map(v=>v.job_type).filter(Boolean))],[rows])
 const filtered=rows.filter(v=>{const hay=`${v.organization} ${v.post} ${v.state} ${v.location} ${v.eligibility}`.toLowerCase();const live=v.live_status||v.status;return (!q||hay.includes(q.toLowerCase()))&&(state==='All'||v.state===state)&&(type==='All'||v.job_type===type)&&(status==='Open + Closed'||live===status)&&(verified==='All'||String(v.verification_status||'').startsWith('Verified'))})
 return <main><Header/><div className="directory"><div className="dirHead"><div><span className="eyebrow">VACANCY DIRECTORY</span><h1>Foundryman vacancies</h1><p>Search and filter the current database. Always confirm the official notification before applying.</p></div><div className="dirCount">{filtered.length}<span>results</span></div></div><div className="filterBar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search post, organization, state…"/><select value={state} onChange={e=>setState(e.target.value)}>{states.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>Open + Closed</option><option>Open</option><option>Closed</option><option>Under Review</option></select><select value={verified} onChange={e=>setVerified(e.target.value)}><option value="All">All verification</option><option value="Verified">Officially verified</option></select></div>{loading?<div className="empty">Loading live database…</div>:<div className="directoryGrid">{filtered.map(v=><Card key={v.vacancy_id} v={v}/>)}</div>}{!loading&&!filtered.length&&<div className="empty">No vacancy matches these filters.</div>}</div><Footer/></main>
}
function Header(){return <header className="topbar"><Link href="/" className="brand"><span className="brandMark">F</span><span><strong>Foundryman Jobs India</strong><small>ITI Foundryman Vacancy Intelligence</small></span></Link><nav><Link href="/">Dashboard</Link><Link href="/vacancies">Vacancies</Link><Link href="/sources">Sources</Link></nav></header>}
function Footer(){return <footer><b>Foundryman Jobs India</b><span>Official-source first</span></footer>}
function Card({v}){const d=v.days_remaining??daysLeft(v.last_date);const live=v.live_status||(d!==null&&d<0?'Closed':v.status);return <article className="vacCard"><div className="cardLine"><span className={`status ${live==='Open'?'open':'closed'}`}>{live}</span><small>{v.vacancy_id}</small></div><Link href={`/vacancies/${v.vacancy_id}`}><h2>{v.post}</h2></Link><b className="orgName">{v.organization}</b><div className="cardMeta"><span>📍 {v.location||v.state||'India'}</span><span>🧰 {v.job_type||'—'}</span>{v.vacancy_count?<span>👥 {v.vacancy_count}</span>:null}</div><div className="evidence"><b>Eligibility:</b> {v.eligibility||'See official notification'}</div><div className="cardFoot"><span>{d===null?'Deadline not stored':d<0?'Expired':d===0?'Due today':`${d} days left`}</span><span>{v.last_date||'Check notice'}</span></div><Link className="detailsLink" href={`/vacancies/${v.vacancy_id}`}>View vacancy →</Link></article>}
