'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { getSupabase } from '../../../lib/supabase'

const css = `.wrap{max-width:1200px;margin:0 auto;padding:48px 24px 80px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;margin-bottom:26px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.16em;color:#00866a}.top h1{font-size:clamp(2.4rem,5vw,4rem);line-height:.98;margin:8px 0 12px;color:#10232d}.top p{color:#60727b;margin:0}.card{background:#fff;border:1px solid #d9e1df;border-radius:18px;padding:22px;box-shadow:0 10px 30px rgba(16,35,45,.05);margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.grid label{font-size:12px;font-weight:800;color:#334952;display:flex;flex-direction:column;gap:6px}.grid .span2{grid-column:span 2}input,select,textarea{width:100%;box-sizing:border-box;border:1px solid #cbd7d4;border-radius:10px;padding:10px 11px;background:#fbfcfc;font:inherit;color:#10232d}textarea{min-height:90px;resize:vertical}.actions{display:flex;gap:9px;justify-content:flex-end;margin-top:18px}.btn{border:1px solid #cbd7d4;border-radius:9px;padding:10px 14px;font-weight:800;cursor:pointer;background:#fff;color:#17303a}.primary{background:#087f62;color:#fff;border-color:#087f62}.danger{color:#a52f28}.table{overflow:auto;border:1px solid #d9e1df;border-radius:14px}table{width:100%;border-collapse:collapse;min-width:1050px}th,td{text-align:left;padding:13px 14px;border-bottom:1px solid #e4e9e7;font-size:13px}th{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#61747c;background:#f5f8f7}td b{color:#10232d}td small{display:block;color:#7a898f;margin-top:3px}.badge{display:inline-flex;padding:5px 8px;border-radius:999px;font-size:11px;font-weight:800;background:#e8f7f1;color:#075c49}.off{background:#eef1f2;color:#52636b}.msg{padding:12px 14px;border-radius:10px;margin-bottom:16px;background:#e8f7f1;color:#075c49}.err{background:#fff0ef;color:#9d2f27}@media(max-width:800px){.grid{grid-template-columns:1fr}.grid .span2{grid-column:span 1}.top{flex-direction:column;align-items:flex-start}}`

const blank={source_name:'',organization:'',official_url:'',recruitment_url:'',source_type:'Govt Official Site',coverage:'India',search_keywords:'Foundryman,ITI Foundryman,Foundryman Apprentice',priority:3,active:true,notes:''}

export default function SourcesAdmin(){
 const sb=useMemo(()=>getSupabase(),[]); const [session,setSession]=useState(null),[authorized,setAuthorized]=useState(false),[checking,setChecking]=useState(true); const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{let mounted=true; (async()=>{const {data}=await sb.auth.getSession(); if(!mounted)return; setSession(data.session); if(data.session){const a=await sb.from('admin_users').select('user_id').eq('user_id',data.session.user.id).eq('active',true).maybeSingle();setAuthorized(!!a.data)} setChecking(false)})(); const {data:l}=sb.auth.onAuthStateChange((_e,s)=>{setSession(s); if(!s){setAuthorized(false);return} sb.from('admin_users').select('user_id').eq('user_id',s.user.id).eq('active',true).maybeSingle().then(r=>setAuthorized(!!r.data))}); return()=>{mounted=false;l.subscription.unsubscribe()}} , [sb])
 useEffect(()=>{if(authorized)load()},[authorized])
 async function load(){setError('');const {data,error}=await sb.from('source_registry').select('*').order('priority').order('source_name');if(error)setError(error.message);else setRows(data||[])}
 function change(e){setForm(f=>({...f,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}))}
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');const payload={...form,priority:Number(form.priority)||5};const r=editing?await sb.from('source_registry').update(payload).eq('id',editing):await sb.from('source_registry').insert(payload);if(r.error)setError(r.error.message);else{setMessage(editing?'Source updated.':'Source added.');setForm(blank);setEditing(null);load()}setBusy(false)}
 function edit(r){setEditing(r.id);setForm({...r})}
 async function remove(r){if(!confirm(`Delete ${r.source_name}?`))return;const {error}=await sb.from('source_registry').delete().eq('id',r.id);if(error)setError(error.message);else{setMessage('Source deleted.');load()}}
 async function signout(){await sb.auth.signOut();location.href='/admin'}
 if(checking)return <main><style>{css}</style><div className="wrap">Loading…</div></main>
 if(!session||!authorized)return <main><style>{css}</style><div className="wrap"><div className="card"><span className="eyebrow">ADMIN ACCESS</span><h1>Not authorized</h1><p>Sign in through the main Admin page first.</p><Link className="btn primary" href="/admin">Go to Admin</Link></div></div></main>
 return <main><style>{css}</style><div className="wrap"><div className="top"><div><span className="eyebrow">SOURCE REGISTRY</span><h1>Monitoring sources</h1><p>Manage official sources used by the free monitoring engine.</p></div><div className="actions"><Link className="btn" href="/admin">Vacancies</Link><Link className="btn" href="/admin/monitoring">Monitoring</Link><button className="btn" onClick={signout}>Sign out</button></div></div>{message&&<div className="msg">{message}</div>}{error&&<div className="msg err">{error}</div>}
 <form className="card" onSubmit={save}><h2>{editing?'Edit source':'Add source'}</h2><div className="grid"><label>Source name<input name="source_name" value={form.source_name} onChange={change} required/></label><label>Organization<input name="organization" value={form.organization||''} onChange={change}/></label><label>Priority<input name="priority" type="number" min="1" max="99" value={form.priority} onChange={change}/></label><label>Official URL<input name="official_url" value={form.official_url} onChange={change} required/></label><label>Recruitment URL<input name="recruitment_url" value={form.recruitment_url||''} onChange={change}/></label><label>Source type<select name="source_type" value={form.source_type} onChange={change}><option>Govt Official Site</option><option>Official Publication</option><option>PSU Official Site</option><option>Railway Official Site</option><option>Other</option></select></label><label>Coverage<input name="coverage" value={form.coverage||''} onChange={change}/></label><label className="span2">Search keywords<textarea name="search_keywords" value={form.search_keywords} onChange={change}/></label><label className="span2">Notes<textarea name="notes" value={form.notes||''} onChange={change}/></label><label>Active<input name="active" type="checkbox" checked={!!form.active} onChange={change}/></label></div><div className="actions"><button type="button" className="btn" onClick={()=>{setEditing(null);setForm(blank)}}>Clear</button><button className="btn primary" disabled={busy}>{busy?'Saving…':editing?'Update source':'Add source'}</button></div></form>
 <section className="card"><h2>{rows.length} sources</h2><div className="table"><table><thead><tr><th>Source</th><th>Coverage</th><th>Priority</th><th>Active</th><th>Last checked</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.source_name}</b><small>{r.organization||''}</small></td><td>{r.coverage||'—'}</td><td>{r.priority}</td><td><span className={`badge ${r.active?'':'off'}`}>{r.active?'Active':'Paused'}</span></td><td>{r.last_checked?new Date(r.last_checked).toLocaleString():'Never'}</td><td><button className="btn" onClick={()=>edit(r)}>Edit</button> <button className="btn danger" onClick={()=>remove(r)}>Delete</button></td></tr>)}</tbody></table></div></section></div></main>
}
