'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {getSupabase} from '../../lib/supabase'
const fallback=[
 {source_name:'Directorate General of Training (DGT)',organization:'Ministry of Skill Development & Entrepreneurship',source_type:'Govt Official Site',coverage:'India',priority:'High',historical_foundryman_evidence:'Foundryman is an officially designated trade; DGT also publishes Foundryman CITS and recruitment-related rules.',official_url:'https://dgt.gov.in/',recruitment_url:'https://dgt.gov.in/en/apprentices-syllabus',active:true},
 {source_name:'CSIR-CMERI',organization:'Council of Scientific & Industrial Research',source_type:'Govt Official Site',coverage:'India',priority:'High',historical_foundryman_evidence:'Technician-I Foundryman recruitment records.',official_url:'https://www.cmeri.res.in/',recruitment_url:'https://www.cmeri.res.in/hi/vacancy',active:true},
 {source_name:'DRDO-DRDL',organization:'Defence Research & Development Organisation',source_type:'Govt Official Site',coverage:'Hyderabad / Defence',priority:'High',historical_foundryman_evidence:'Official DRDL ITI Apprenticeship notifications explicitly include Foundryman.',official_url:'https://drdo.gov.in/',recruitment_url:'https://drdo.gov.in/drdo/en/offerings/vacancies/drdl-hyderabad-invites-applications-engagement-iti-apprentices-training-year',active:true},
 {source_name:'BHEL Haridwar',organization:'Bharat Heavy Electricals Limited',source_type:'Govt Official Site',coverage:'Haridwar / Uttarakhand',priority:'High',historical_foundryman_evidence:'Artisan Recruitment - Foundryman Trade records.',official_url:'https://hwr.bhel.com/',recruitment_url:'https://hwr.bhel.com/recruitment/',active:true},
 {source_name:'West Central Railway',organization:'Indian Railways',source_type:'Govt Official Site',coverage:'Jabalpur / Bhopal / Kota',priority:'High',historical_foundryman_evidence:'Blacksmith (Foundryman) apprenticeship explicitly listed.',official_url:'https://wcr.indianrailways.gov.in/',recruitment_url:'https://wcr.indianrailways.gov.in/',active:true},
 {source_name:'UPSC',organization:'Union Public Service Commission',source_type:'Govt Official Site',coverage:'India',priority:'High',historical_foundryman_evidence:'Training Officer (Foundryman/Moulder) recruitment under DGT.',official_url:'https://upsc.gov.in/',recruitment_url:'https://upsc.gov.in/recruitment',active:true},
 {source_name:'Employment News',organization:'Government of India',source_type:'Govt Official Site',coverage:'India',priority:'Medium',historical_foundryman_evidence:'Government recruitment notices and historical Foundryman-related listings.',official_url:'https://employmentnews.gov.in/',recruitment_url:'https://employmentnews.gov.in/',active:true},
 {source_name:'Apprenticeship India',organization:'Government of India',source_type:'Govt Official Site',coverage:'India',priority:'High',historical_foundryman_evidence:'Official apprenticeship ecosystem including Foundryman trade opportunities.',official_url:'https://www.apprenticeshipindia.gov.in/',recruitment_url:'https://www.apprenticeshipindia.gov.in/',active:true}
]
export default function Sources(){const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const sb=getSupabase();if(!sb){setRows(fallback);setLoading(false);return}const{data,error}=await sb.from('sources').select('*').order('priority',{ascending:true});setRows(error||!data?.length?fallback:data);setLoading(false)})()},[]);return <main><Header/><div className="sourcesPage"><div className="dirHead"><div><span className="eyebrow">SOURCE REGISTRY</span><h1>Monitored recruitment sources</h1><p>Sources are discovery inputs. Official notifications remain the final verification authority.</p></div><div className="dirCount">{rows.length}<span>sources</span></div></div>{loading?<div className="empty">Loading source registry…</div>:<div className="sourceGrid">{rows.map(s=><article className="sourceCard" key={s.source_name}><div className="cardLine"><span className={`priority ${String(s.priority).toLowerCase()}`}>{s.priority||'Medium'} priority</span><span className="activeDot">● {s.active===false?'Inactive':'Active'}</span></div><h2>{s.source_name}</h2><b>{s.organization}</b><p>{s.historical_foundryman_evidence}</p><div className="sourceMeta"><span>Coverage: {s.coverage||'India'}</span><span>Type: {s.source_type||'Official'}</span></div><div className="cardActions">{s.official_url&&<a href={s.official_url} target="_blank" rel="noreferrer">Official site ↗</a>}{s.recruitment_url&&<a href={s.recruitment_url} target="_blank" rel="noreferrer">Recruitment ↗</a>}</div></article>)}</div>}</div><Footer/></main>}
function Header(){return <header className="topbar"><Link href="/" className="brand"><span className="brandMark">F</span><span><strong>Foundryman Jobs India</strong><small>ITI Foundryman Vacancy Intelligence</small></span></Link><nav><Link href="/">Dashboard</Link><Link href="/vacancies">Vacancies</Link><Link href="/sources">Sources</Link></nav></header>}
function Footer(){return <footer><b>Foundryman Jobs India</b><span>Official-source first</span></footer>}
