const SUPABASE_URL = process.env.SUPABASE_URL?.replace(/\/$/, '')
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!SUPABASE_URL || !SERVICE_KEY) throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
const headers={apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`, 'Content-Type':'application/json'}
async function api(path,opts={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...opts,headers:{...headers,...(opts.headers||{})}});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.status===204?null:r.json()}
function esc(s){return String(s||'').replace(/\s+/g,' ').trim()}
function terms(s){return String(s||'').split(',').map(x=>esc(x).toLowerCase()).filter(Boolean)}
function fingerprint(url,title){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${url}|${title}`)).then(b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join(''))}
function links(html,base){const out=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let href=m[1];if(href.startsWith('/'))href=new URL(href,base).href;else if(href.startsWith('./'))href=new URL(href,base).href;if(!/^https?:\/\//i.test(href))continue;const title=esc(m[2].replace(/<[^>]+>/g,' '));if(title)out.push({url:href,title})}return out}
async function main(){const sources=await api('source_registry?active=eq.true&select=*&order=priority.asc');const run=(await api('monitoring_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'Running'})}))[0];let checked=0,pages=0,candidates=0,errors=0;for(const s of sources){checked++;const url=s.recruitment_url||s.official_url;try{const resp=await fetch(url,{redirect:'follow',headers:{'user-agent':'FoundrymanJobsMonitor/1.0'}});const html=await resp.text();pages++;const allTerms=terms(s.search_keywords);const lower=html.toLowerCase();const matched=allTerms.filter(t=>lower.includes(t));const found=links(html,url).filter(x=>{const hay=`${x.title} ${x.url}`.toLowerCase();return allTerms.some(t=>hay.includes(t))});for(const item of found.slice(0,25)){const fp=await fingerprint(item.url,item.title);try{await api('vacancy_candidates',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({source_id:s.id,monitoring_run_id:run.id,title:item.title,url:item.url,matched_keywords:matched.join(', '),snippet:`Matched source keyword on ${s.source_name}. Official eligibility still requires manual verification.`,source_status:`HTTP ${resp.status}`,eligibility_status:'Needs Verification',review_status:'Pending Review',fingerprint:fp})});candidates++}catch(e){if(!String(e.message).includes('duplicate'))throw e}}await api(`source_registry?id=eq.${s.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_checked:new Date().toISOString(),last_status:`HTTP ${resp.status}`,last_error:null,updated_at:new Date().toISOString()})})}catch(e){errors++;await api(`source_registry?id=eq.${s.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_checked:new Date().toISOString(),last_status:'ERROR',last_error:String(e.message).slice(0,500),updated_at:new Date().toISOString()})})}}await api(`monitoring_runs?id=eq.${run.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({finished_at:new Date().toISOString(),sources_checked:checked,pages_scanned:pages,candidates_found:candidates,errors_count:errors,status:errors===checked?'Failed':'Completed',notes:'Free-tier direct source scan. Candidates require official verification before publication.'})});console.log(JSON.stringify({checked,pages,candidates,errors}))}
main().catch(e=>{console.error(e);process.exit(1)})
