'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { getSupabase } from '../../../lib/supabase'

const fallback = {
 'FM-2026-001': { vacancy_id:'FM-2026-001', organization:'CSIR-CMERI', department:'Council of Scientific & Industrial Research', post:'Technician-I (Group-II) - Foundryman', recruitment:'Direct Recruitment', notification_number:'01/2026', vacancy_count:null, state:'West Bengal', location:'Durgapur', job_type:'Permanent', status:'Closed', verification_status:'Verified - Official Doc', eligibility:'ITI Foundryman', qualification:'ITI / relevant prescribed qualification as per official advertisement', last_date:'2026-09-13', official_notification_url:'https://www.cmeri.res.in/hi/vacancy', official_apply_url:null, foundryman_eligibility_evidence:'Official CSIR-CMERI vacancy page lists Technician-I recruitment and Foundryman trade eligibility.', selection_process:'As per official recruitment notification' },
 'FM-2026-002': { vacancy_id:'FM-2026-002', organization:'DRDO-DRDL', department:'Defence Research & Development Organisation', post:'ITI Apprentice - Foundryman', recruitment:'ITI Apprenticeship Training 2026-27', notification_number:null, vacancy_count:null, state:'Telangana', location:'DRDL, Hyderabad', job_type:'Apprenticeship', status:'Closed', verification_status:'Verified - Official Doc', eligibility:'ITI Foundryman', qualification:'ITI Pass in Foundryman trade', last_date:'2026-01-29', official_notification_url:'https://www.drdo.gov.in/drdo/sites/default/files/vacancy/advtDRDL15012026.pdf', official_apply_url:'https://www.apprenticeshipindia.gov.in/', foundryman_eligibility_evidence:'Official DRDL notification explicitly lists Foundryman among ITI apprentice trades.', selection_process:'As per Apprenticeship selection process' },
 'FM-2026-003': { vacancy_id:'FM-2026-003', organization:'West Central Railway', department:'Indian Railways', post:'Blacksmith (Foundryman) Apprentice', recruitment:'Act Apprentice 2025-26', notification_number:'01/2025', vacancy_count:139, state:'Madhya Pradesh', location:'Jabalpur / Bhopal / Kota', job_type:'Apprenticeship', status:'Closed', verification_status:'Verified - Official Doc', eligibility:'Foundryman / Blacksmith (Foundryman)', qualification:'ITI qualification as prescribed in official apprenticeship notification', last_date:null, official_notification_url:'https://wcr.indianrailways.gov.in/', official_apply_url:null, foundryman_eligibility_evidence:'Official WCR notification explicitly lists Blacksmith (Foundryman), with 139 total slots.', selection_process:'As per Railway Act Apprentice rules' },
 'FM-2026-004': { vacancy_id:'FM-2026-004', organization:'BHEL Haridwar', department:'Bharat Heavy Electricals Limited', post:'Artisan - Foundryman', recruitment:'Artisan Recruitment 2026', notification_number:null, vacancy_count:null, state:'Uttarakhand', location:'Haridwar', job_type:'Permanent', status:'Closed', verification_status:'Verified - Official Doc', eligibility:'ITI Foundryman', qualification:'ITI Foundryman as prescribed by BHEL notification', last_date:null, official_notification_url:'https://hwr.bhel.com/recruitment/', official_apply_url:null, foundryman_eligibility_evidence:'BHEL Haridwar recruitment records identify Foundryman trade.', selection_process:'Document Verification / Skill Test as applicable' },
 'FM-2026-005': { vacancy_id:'FM-2026-005', organization:'UPSC / DGT', department:'Directorate General of Training, Ministry of Skill Development & Entrepreneurship', post:'Training Officer - Foundryman/Moulder', recruitment:'UPSC Recruitment', notification_number:'Advertisement No. 06/2025', vacancy_count:1, state:'All India', location:'DGT / All India service liability', job_type:'Permanent', status:'Closed', verification_status:'Verified - Official Doc', eligibility:'Foundryman / Moulder', qualification:'As prescribed in UPSC/DGT recruitment rules and advertisement', age_limit:'30 years for UR as stated in advertisement', salary_stipend:'Level-07 Pay Matrix', last_date:null, official_notification_url:'https://upsc.gov.in/recruitment', official_apply_url:null, foundryman_eligibility_evidence:'UPSC advertisement identifies one Training Officer vacancy for Foundryman/Moulder under DGT.', selection_process:'As per UPSC recruitment process' }
}
function daysLeft(date){if(!date)return null;const a=new Date();a.setHours(0,0,0,0);return Math.ceil((new Date(date+'T00:00:00')-a)/86400000)}
export default function VacancyDetail({params}){
 const [v,setV]=useState(null),[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const id=params?.id;const sb=getSupabase();if(sb){const {data,error}=await sb.from('vacancy_dashboard').select('*').eq('vacancy_id',id).maybeSingle();if(!error&&data){setV(data);setLoading(false);return}}setV(fallback[id]||null);setLoading(false)})()},[params])
 if(loading)return <main><Header/><div className="detail"><div className="empty">Loading vacancy…</div></div></main>
 if(!v)return <main><Header/><div className="detail"><div className="empty">Vacancy not found. <Link href="/vacancies">Back to directory</Link></div></div></main>
 const d=v.days_remaining??daysLeft(v.last_date); const live=v.live_status||(d!==null&&d<0?'Closed':v.status)
 return <main><Header/><div className="detail"><Link className="back" href="/vacancies">← Back to vacancies</Link><div className="detailGrid"><article className="detailMain"><div className="cardLine"><span className={`status ${live==='Open'?'open':'closed'}`}>{live}</span><small>{v.vacancy_id}</small></div><h1>{v.post}</h1><div className="detailOrg">{v.organization}</div><div className="detailChips"><span>📍 {v.location||v.state||'India'}</span><span>🧰 {v.job_type||'—'}</span>{v.vacancy_count?<span>👥 {v.vacancy_count} vacancies</span>:null}</div><section><h2>Foundryman eligibility evidence</h2><div className="evidenceBig">{v.foundryman_eligibility_evidence||'See official notification.'}</div></section><section><h2>Recruitment details</h2><div className="detailTable"><Row l="Department" v={v.department}/><Row l="Recruitment" v={v.recruitment}/><Row l="Notification" v={v.notification_number}/><Row l="Qualification" v={v.qualification}/><Row l="Age limit" v={v.age_limit}/><Row l="Salary / stipend" v={v.salary_stipend}/><Row l="Selection" v={v.selection_process}/></div></section></article><aside className="actionPanel"><div className="panelLabel">APPLICATION</div><h2>{d===null?'Check official notice':d<0?'Application closed':d===0?'Deadline today':`${d} days remaining`}</h2>{v.last_date&&<p>Last date: <b>{v.last_date}</b></p>}<div className="actionStack">{v.official_notification_url&&<a className="primary wide" href={v.official_notification_url} target="_blank" rel="noreferrer">Official notification ↗</a>}{v.official_apply_url&&<a className="secondary wide" href={v.official_apply_url} target="_blank" rel="noreferrer">Official apply link ↗</a>}</div><div className="verifyBox"><b>✓ {String(v.verification_status||'').startsWith('Verified')?'Officially verified':'Verification pending'}</b><span>Always read the latest official notification before applying.</span></div></aside></div></div><Footer/></main>
}
function Header(){return <header className="topbar"><Link href="/" className="brand"><span className="brandMark">F</span><span><strong>Foundryman Jobs India</strong><small>ITI Foundryman Vacancy Intelligence</small></span></Link><nav><Link href="/">Dashboard</Link><Link href="/vacancies">Vacancies</Link><Link href="/sources">Sources</Link></nav></header>}
function Footer(){return <footer><b>Foundryman Jobs India</b><span>Official-source first</span></footer>}
function Row({l,v}){if(!v)return null;return <div><span>{l}</span><b>{v}</b></div>}
